---
name: accunts_api
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
  sdk: '>=2.19.4 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  mysql1: ^0.20.0
  path_provider: ^2.0.14
  dio: ^5.1.1
  curved_navigation_bar: ^1.0.3
  gallery_saver: ^2.3.2
  gsheets: ^0.4.2
  cupertino_icons: ^1.0.2
  image_picker: ^0.8.5+3
  open_file: ^3.3.1
  syncfusion_flutter_xlsio: ^20.4.52-beta
  http:
  flutter_form_builder: ^7.1.0
  permission_handler: ^10.2.0
  image_cropper: ^3.0.2
  firebase_storage: ^11.1.0
  shared_preferences: ^2.0.15
  cloud_firestore: ^4.5.0
  firebase_database: ^10.1.0
  flutter_data: ^1.5.9
  csv: ^5.0.1
  flutter_local_notifications: ^14.1.0
  universal_html: ^2.2.1
  file_picker: ^5.3.0
  fluttertoast: ^8.2.1
  pull_to_refresh: ^2.0.0
  flutter_slidable: ^3.0.0
  printing: ^5.10.3
  pdf: ^3.10.1
  flutter_document_picker: ^5.1.0
  intl: ^0.17.0
  firebase_auth: ^4.4.0
  firebase_core: ^2.9.0
  flutter_launcher_icons: ^0.13.1
  uuid: ^3.0.4
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/xyma.png"
  min_sdk_android: 21

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_svg: ^2.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
